name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ec2-13-218-184-185.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum update -y
            sudo yum install -y httpd
            sudo systemctl enable httpd
            sudo systemctl start httpd
            sudo rm -rf /var/www/html/*
            cd /tmp
            git clone https://github.com/MichelBarcellos/pipe-app.git
            sudo cp -r pipe-app/* /var/www/html/
            sudo rm -rf pipe-app
            sudo chown -R apache:apache /var/www/html/
            sudo chmod -R 755 /var/www/html/
            sudo systemctl restart httpd
            sudo systemctl status httpd